<img class="img" src="img/aranha1.jpg" rcset style="width: 1305px; height: 400px;">
<h1 class="titulo">Aranhaverso</h1>
<p class="text">O universo que cerca o Homem-Aranha, conhecido também como Aranhaverso ou Spiderverse, é bem variado e envolve uma gama de versões alternativas do herói, com diferentes histórias de origem e gêneros, que são representantes de inúmeras realidades.</p>
<p class="text">Os fãs mais assíduos já estão familiarizados com esse conceito, mas quem é mais casual e não acompanha as HQ’s do “Teioso”, ou mesmo quem só conhece os filmes do herói, pode não entender muito bem o motivo de existirem tantas facetas diferentes do personagem.</p>
<p class="text">A grande verdade é que a Marvel dedicou muitos anos tentando expandir a marca Homem-Aranha além de Peter Parker, com diferentes homens, mulheres e até mesmo alguns animais interpretando o herói.</p>
<p class="text">Todas essas variantes deram origem ao arco Aranhaverso das HQ’s, uma saga que se passou em 2014, durante as edições 9 a 15 da revista “The Amazing Spider-Man”, e em outros títulos que são voltados para suas versões alternativas, como Miles Morales do universo Ultimate e a Mulher-Aranha (Jessica Drew), por exemplo.</p>
<img class="img" src="img/aranha2.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">Esse evento foi responsável por resgatar e reunir, praticamente todas as versões do Homem-Aranha que já foram vistas na mídia, incluindo quadrinhos, séries televisivas, filmes e games.”O que vc acha de tantos Homens Aranha em uma mesma história?”. A ideia era prestar homenagem à criatividade de todos aqueles que já trabalharam com o “Cabeça de Teia” ao longo dos anos, até mesmo em suas versões mais bizarras, e ao mesmo tempo, uni-los em uma grande aventura.</p>
<p class="text">O arco também nos apresentou à novos personagens, como a Teia de Seda ou Silk (Cindy Moon, que foi mordida pela mesma aranha que Peter Parker), a Spider-Gwen (uma versão de Gwen Stacy que foi mordida no lugar de Peter) e May Parker (filha de Peter e Mary Jane vinda em outra realidade).</p>
<p class="text">O Aranhaverso nos quadrinhos da Marvel, foi idealizado pelo roteirista Dan Slott e pelo desenhista Olivier Coipel, acontecendo por aproximadamente 30 edições no total.</p>
<p class="text">Com base em um conceito estabelecido pelo quadrinista J. Michael Straczynski, que trabalhou nas HQ’s do Homem-Aranha por mais de uma década, Slott explorou a ideia de que heróis e vilões que tem seus poderes representados por animais, possuem um Totem relacionado a este animal.</p>
<img class="img" src="img/aranha3.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">Essas pessoas carregam a essência destes seres vivos na natureza, através das várias realidades, sendo responsáveis por fazer a conexão e manter o equilíbrio entre os reinos humano e animal.Dessa maneira, todos os universos alternativos teriam seu representante deste mesmo Totem, cada um com as características próprias do seu mundo de origem.</p>
<p class="text">Ao fazer uma publicação em seu perfil no Twitter, Dan Slott declarou que a história também foi fortemente influenciada pelo jogo “Spider-Man Shattered Dimensios” lançado em 2010 com versões para Nintendo DS, PlayStation 3, Wii, Xbox 360 e PC.Conhecido originalmente como “Spiderverse”, a história pode ser encontrada no Brasil em “O Espetacular Homem-Aranha #7 – #12” de 2016, e também nos encadernados “O Espetacular Homem-Aranha: Prelúdio para o AranhaVerso” e “O Espetacular Homem-Aranha: Aranhaverso”, ambos publicados em 2019</p>
<p class="text">Vale lembrar que todos os compilados foram publicados pela editora Panini, sendo possível ler apenas o arco separadamente. Contudo, a história fica muito mais interessante se toda a fase do autor for acompanhada.Mesmo com alguns furos de roteiro e pequenos deslises, é uma história incrível para aqueles que se divertem com HQ’s de aventura e tramas complexas envolvendo viagens pelo multiverso.</p>
<p class="text">Dan Slott é muito habilidoso ao criar e reaproveitar versões do Homem-Aranha, conseguindo equilibrar muito bem o tempo de cada uma delas.O autor foi feliz ao abraçar o “absurdo” em uma trama colossal, onde até robôs gigantes, como o poderoso Leopardon de Takuya Yamashiro, tem o seu momento.</p>
<img class="img" src="img/aranha4.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">A história do Aranhaverso nos quadrinhos, teve seu início a partir da controversa, mas popular história, na qual o Doutor Octopus conseguiu transferir sua mente para o corpo de Peter, após viajar para o ano de 2099.Esta versão do herói ficou conhecida como Homem-Aranha Superior, que na verdade, é o personagem central deste, que se tornou um dos arcos mais importantes e representativos das HQ’s do personagem.Contudo, seu retorno ao passado, pulando através das diferentes realidades pelo multiverso, o levou a um ponto no qual Parker conseguiu recuperar novamente o controle sobre seu corpo, e dessa forma, dois Peters da Terra-616 acabaram participando do evento.</p>
<p class="text">Morlun é um velho conhecido do Homem-Aranha, que inclusive já foi derrotado mais de uma vez pelo herói, sendo apresentado pela primeira vez, na revista “O Espetacular Homem-Aranha: De Volta Ao Lar“, publicada em 2001.O vilão é uma espécie de vampiro multiversal que se alimenta da força vital dos seres vivos. Entretanto, ele necessita de uma fonte genuína dessa energia para sobreviver, assim como a que os Totens possuem.O mais puro elo de ligação existente entre humanos e animais é o Totem da Aranha, que por várias gerações, sempre possuiu uma personificação, sendo que atualmente no universo 616 da Marvel, é representada por Peter Parker.</p>
<p class="text">Durante o Aranhaverso descobrimos que Morlun é na verdade, um dos integrantes de um clã conhecido como Os Herdeiros, uma família de seres caçadores, que também se alimentam da energia vital dos Totens, principalmente das aranhas.Na história “Pecado Original“, publicada em 2014, que tem início com a morte do Vigia Uato, Peter Parker fica sabendo que a mesma aranha que o picou anos atrás, também picou Cindy Moon.A garota foi mantida em um bunker pelos últimos treze anos por Ezekiel Sims, um Totem Aranha que já havia estudado os métodos de Morlun, e estava tentando protegê-la de também ser caçada pelo vilão.</p>
<p class="text">Sem saber sobre os planos de Ezekiel, Peter decide ir ao encontro de Cindy e retira-la de seu aprisionamento, mas ao mesmo tempo, acaba despertando os sentidos de Morlun, fazendo com que ele descobra sua localização.Percebendo que a jovem (mais tarde conhecida como Teia de Seda) foi libertada pelo Homem-Aranha, o vilão declara que “A Grande Caçada” iria começar, onde ele e sua família deveriam matar todos os Totens Aranhas existentes no Multiverso.Toda essa empreitada dos vilões, está relacionada com uma antiga profecia que dizia que “derrotando O Outro, A Noiva (Cindy Moon) e O Descendente, nunca mais surgiriam Totens Aranhas” e dessa forma, os Herdeiros poderiam viver eternamente.</p>
<img class="img" src="img/aranha5.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">Em um passado distante, Morlun e sua família, composta pelos irmãos Bora, Verna, Brix, Daemos, Jennix e Karn, o Patriaca Solus e a Matriarca, participaram em uma batalha contra a divindade conhecida como Mestre Tecelão da Terra 001.Esta entidade é responsável por tecer a teia do Multiverso, sendo uma espécie de guardião, que mantem as portas das diferentes realidades conectadas entre si, para que a vida possa fluir naturalmente entre elas.</p>
<p class="text">O clã formado pelos vilões teve sucesso em escraviza-lo e utilizar seu poder para viajar entre as várias dimensões existentes, e dessa forma poder caçar e absorver cada um dos Totens Aranha.</p>
<p class="text">Como os Herdeiros mataram vários Totens com poderes aracnídeos, o Homem-Aranha de Otto Octavius (ou Homem-Aranha Superior), que descobriu uma forma de saltar entre as realidades, decidiu reunir uma equipe formada por versões alternativas do “Cabeça de Teia” para lutar contra os poderosos irmãos.O grande problema é que mesmo matando os Herdeiros, eles sempre ressurgem novamente, como se fossem imortais.</p>
<p class="text">Isso ocorre, pois todos possuem uma enorme quantidade de clones, produzidos na Terra 802, que recebem sua essência, toda vez que são mortos.Enquanto a Grande Caçada ocorre, o Exército-Aranha formado pelo Homem-Aranha Superior e suas várias frentes de ataque, deverão encontrar uma maneira eficaz de derrotar Morlun, Karn, e o resto dos Herdeiros de uma vez por todas.</p>
<img class="img" src="img/aranha6.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">Homem-Aranha: Através do Aranhaverso, é a continuação do vencedor do Oscar Homem-Aranha: No Aranhaverso, de 2018, que acompanha Miles Morales (Shameik Moore), o simpático Homem-Aranha do Brooklyn. Neste novo capítulo, Miles está de volta para uma nova missão em sua agitada vida como super herói. No novo filme, Morales é transportado para uma aventura épica através do multiverso, e deve unir forças com a mulher-aranha Gwen Stacy (Hailee Steinfeld) e um novo time de Pessoas-Aranha, formado por heróis de diversas dimensões. No entanto, tudo muda quando os heróis entram em conflito sobre como lidar com uma nova ameaça, e Miles se vê em um impasse. E para piorar ainda mais a situação, eles precisam enfrentar um vilão muito mais poderoso do que qualquer coisa que já tenham encontrado antes. Agora, para salvar as pessoas que ele mais ama no mundo, Miles deve redefinir o que significa ser um super herói.</p>
<p class="text"></p>
<p class="text"></p>
<p class="text"></p>
<img class="img" src="img/aranha7.jpg" rcset style="width: 1305px; height: 400px;">
<a href="?page=marvels.php">Acessar a Comunidade Nerd</a>
