<img class="img" src="img/guardioes1.jpg" rcset style="width: 1305px; height: 400px;">
<h1 id="marvel">Guardiões da Galáxia</h1>
<h2 id="marvel2">Volume 3</h2>
<p class="text">Os Guardiões da Galáxia foram idealizados por Peter Quill , o lendário Star-Lord, como uma equipe pró-ativa para proteger o cosmos. Quill idealizou a equipe à luz de duas crises subsequentes que forçaram heróis independentes a improvisar uma resistência quando a galáxia foi ameaçada, a saber, a incursão da Onda de Aniquilação e a conquista do Império Kree pela Falange . Os Guardiões da Galáxia geralmente transitam entre ser uma força policial sancionada no espaço ou um grupo de mercenários fora da lei. Esperando que ninguém mais faça seu trabalho heróico, seu objetivo é proteger civilizações inocentes de serem destruídas ou escravizadas por invasores oportunistas.</p>
<img class="img" src="img/guardioes2.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">Considerando que os heróis cósmicos independentes foram forçados a unir suas forças para combater a incursão de Aniquilador e sua Onda de Aniquilação no universo [5] e Ultron e a conquista do Império Kree por Phalanx , [6] Peter Quill , o campeão lendariamente conhecido como o Star-Lord, decidiu estabelecer uma força proativa para proteger a galáxia sem improvisação. Por recomendação de seu aliado Nova , o Foguete Humano, Quill estabeleceu uma base de operações para seu grupo potencial na estação neutra Luganenhum . , que convenientemente tinha um sistema de teletransporte com alcance quase universal, um cachorro soviético inteligente e psíquico chamado Cosmo como seu chefe de segurança e ligação galáctica para a nova equipe [4] e a equipe de super-heróis conhecida como Luminals of Xarth , que se tornou rivais e vizinhos de Quill.</p>
<p class="text">Para sua equipe, Quill recrutou ex-companheiros de equipe e criminosos condenados anteriores com quem havia trabalhado em uma missão especial para o Império Kree durante a conquista do Phalanx: [8] o especialista em armas e gênio tático Rocket e o conselheiro psíquico Mantis . Além disso, ele recrutou os heróis cosmicamente poderosos que também desempenharam papéis durante as crises anteriores, ou seja, Phyla-Vell , o Protetor do Universo chamado Quasar e portador das Bandas Quânticas , e o recentemente renascido Warlock , um feiticeiro cósmico e ex-possuidor de as Joias do Infinito . Os assassinos mortais Gamora, que tinha a reputação de ser a mulher mais perigosa da galáxia, e Drax, o Destruidor, reuniu a equipe.</p>
<p class="text">Em sua primeira missão, o grupo entrou em conflito com a revitalizada Igreja Universal da Verdade em seu gigantesco templo para impedir sua brutal jornada de conversão forçada de pessoas à sua fé. Durante a provação catastrófica, Warlock percebeu que o tecido do espaço-tempo estava fragilizado devido a tantas agressões, abrindo caminho para intrusos invadirem o universo. [4] Um desses invasores veio na forma de uma massa de "Limbo Ice", que revelou um campeão semi-amnésico que se identificou como Major Vance Astro , dos Guardiões da Galáxia de mil anos no futuro . A declaração de Astro inspirou Rocket a batizar sua equipe sem nome de ' Guardiões da Galáxia' .</p>
<p class="text">Os Guardiões então confrontaram os Cardeais da Igreja Universal da Verdade em outro templo, enquanto Astro foi alvejado a bordo de Luganenhum por Starhawk . [9] As coisas pioraram quando Luganenhum foi infiltrado por Skrulls metamorfos , incitando a desconfiança entre a equipe e os Luminals, já que Luganenhum foi colocado sob um bloqueio. Simultaneamente, Warlock se preocupou com o fato de a equipe não ter permissão para agir de forma independente dentro de Luganenhum e Drax foi desonesto depois de saber que Quill havia instruído Mantis a coagir telepaticamente os membros dos Guardiões da Galáxia a se juntarem à sua iniciativa sem questionar. [7]Usando um disruptor de sinapse, Drax assassinou todos os seres em Luganenhum por um período limitado de tempo em um processo que revelou os Skrulls a bordo. A situação se intensificou com outro ataque de outra versão do Starhawk . Embora os Skrulls tenham se mostrado pacifistas e Starhawk tenha sido preso, esses eventos levaram à revelação pública de que Quill havia adulterado a mente de seus companheiros de equipe, algo que corroeu a equipe.</p>
<p class="text">Com a maioria dos membros deixando a equipe, Rocket manteve os Guardiões da Galáxia vivos com Mantis, Astro e seus ex-aliados, o colossal Groot e o galante guerreiro do Microverse Bug , para lutar contra os Badoon no Império Spartax . Enquanto isso, Quill tornou-se prisioneiro do brutal Blastaar na Zona Negativa [11] após ser banido pelo Kree Accuser Ronan . [12] Desejando acessar a Terra, Blastaar fez Quill cercar a prisão sobre-humana abandonada conhecida como 42 , criada pela Iniciativa.para abrigar as forças anti-registro. Quill se juntou à rebelião liderada por Jack Flag e contatou os Guardiões para obter ajuda. Flag o direcionou a um telepata que conseguiu entrar em contato com Mantis e fazer os Guardiões se teletransportarem para a Zona Negativa para ajudar a afastar o ataque de Blastaar. [13] Depois de resgatar Quill, os Guardiões escaparam da Zona Negativa, mantendo seu acesso ao universo fechado. Jack Flag ficou com a equipe para suas próximas aventuras.</p>
<img class="img" src="img/guardioes3.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">Os ex-membros dos Guardiões partiram para suas próprias missões, separados dos Guardiões. Warlock e Gamora enfrentaram a Igreja Universal da Verdade, com Warlock planejando liderá-los, pois havia previsto que outra guerra estouraria entre os impérios Kree e Shi'ar. Enquanto isso, ao procurar a garota humana Cammi , Drax e Quasar descobriram que seu destino estava entrelaçado com Moondragon , filha de Drax e amante de Quasar que havia falecido desde a conquista do império Kree por Ultron. Com a intervenção de Mentor , [15] Drax e Quasar foram para o reino de Oblivion , onde Phyla-Vell sentiu falta de suas bandas quânticas que a capacitaram como Quasar. Em sua confusão, eles foram emboscados por Maelstrom, que empunhava as Bandas Quânticas. [16] Durante a luta, o Dragão da Lua consumiu Phyla-Vell. Enquanto Drax continuava a resistir ao Maelstrom, o Quasar original, Wendell Vaughn , veio em seu socorro. Como Mártir, Phyla-Vell saiu da barriga do Dragão com um Moondragon revivido . Mártir concordou secretamente em se tornar o novo avatar da Morte na barriga da besta para devolver Moondragon.</p>
<p class="text">Os Guardiões da Galáxia se reuniram como uma operação para se preparar para a guerra entre o Imperador Shi'ar Vulcano , um usurpador mutante , e a Família Real Inumana , governada pelo Rei dos Kree Raio Negro . Warlock esperava que sua guerra prejudicasse ainda mais a estrutura do universo, levando os Guardiões da Galáxia a tentar impedir os ataques iminentes. Eles se separaram para discutir diplomaticamente as consequências da guerra com os dois lados. A equipe de Rocket foi atacada por Vulcan ao sabotar suas agressões, mas foram resgatados e se juntaram aos Starjammers . [18] Juntas, as duas equipes dominaram a Guarda Imperial Shi'ar e tiveram seu poderosoGladiator se junta a sua causa para depor Vulcan e restaurar o trono para Majestrix Lilandra .</p>
<p class="text">Na seção Kree, a equipe de Quill falhou em convencer os Inumanos a cessar o fogo. De volta a Luganenhum, os Guardiões foram seguidos pela Guarda Imperial e os Inumanos, já que Warlock foi marcado magicamente pela guarda bruxa Magique e Mártir tomou a princesa Inumana Crystal como refém. [20] Os Inumanos partiram após resgatar Crystal, e os Guardiões lidaram com a Guarda Imperial sozinhos em Luganenhum. Warlock manifestou secretamente seu futuro eu maligno, o Magus, para ajudar os Guardiões da Galáxia a expulsar os invasores. Simultaneamente, Moondragon foi influenciada a libertar Starhawk de sua prisão, o que lhe permitiu sequestrar alguns Guardiões e levá-los a uma jornada através do fluxo do tempo em outra tentativa de evitar o colapso do tecido da existência.</p>
<p class="text">Como Majestrix Lilandra havia sido assassinada, [22] um ataque direto contra Vulcano se fez necessário. Os Inumanos lançaram uma Bomba Terrígena para a Galáxia Shi'ar. [23] Detonada pelo sacrifício de Raio Negro, a bomba causou a morte de Vulcano [24] e abriu uma fenda dimensional no universo que foi chamada de Falha . No futuro, os Guardiões sequestrados por Starhawk encontraram suas contrapartes do século 31 e descobriram que a Falha havia causado graves danos no fluxo do fluxo do tempo. Eles emitiram uma mensagem para Warlock para impedir que a Falha se expandisse. [25]No presente, os Guardiões da Galáxia restantes uniram forças com a Realeza Inumana para avaliar a Falha enquanto Warlock usava os motores de fé da Igreja Universal para se fortalecer e estabilizar a fissura. Warlock teve sucesso em seu feitiço, mas foi imediatamente assassinado por Martyr. Em retaliação, Gamora matou Martyr, mas foi eliminado pelo próprio Warlock, que ascendeu como o Magus.</p>
<p class="text">No futuro, os Guardiões da Galáxia aprenderam sobre a ascensão do Magus. [27] Com a ajuda de Kang, o Conquistador , os Guardiões foram enviados de volta no tempo para parar o Magus, pois ele forçaria todas as possibilidades a convergirem. Empunhando um Cubo Cósmico presenteado por Kang, Quill tentou evitar a morte de seus companheiros de equipe, mas falhou porque vários Guardiões foram assassinados pelo Magus. No final, Quill matou Warlock com um tiro, acabando com a ameaça do Magus.</p>
<img class="img" src="img/guardioes4.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">Durante as aventuras que se seguiram, os membros dos Guardiões da Galáxia sofreram grandes mudanças. Drax desistiu da violência depois que sua imprudência brutal causou a morte de escravos inocentes que ele pretendia salvar. [110] Groot foi atacado pelo Jardineiro , que havia sido enlouquecido por Loki, o Deus do Mal, e usou o corpo de Groot para construir um exército de criaturas retorcidas semelhantes a árvores [111] que impediu Groot de regenerar todo o seu corpo e o deixou preso em um tamanho pequeno. [112] Gamora foi assombrada em seus pesadelos por uma fração de sua alma que havia sido perdida por anos no perturbado Soulworld dentro da Joia da Alma e decidiu readquirir a Joia do Infinito.[113] Quill fez o grupo realizar uma última missão juntos antes que eles pudessem trilhar seu próprio caminho.</p>
<p class="text">As atividades dos Guardiões como bandidos os fizeram entrar em conflito com a Tropa Nova, que aplica a lei. Durante sua última missão, uma tarefa que os Guardiões assumiram em nome do Grão-Mestre , eles roubaram uma nave da Nova Corps anteriormente pertencente à Fraternity of Raptors [115] e a renomearam como Milano . Como parte de um assalto, os Guardiões coletaram um universo em miniatura de Citopia para o Grande Mestre. O Grande Mestre então enviou os Guardiões para roubar o Ovo do Monarca Hujahdarian da coleção do Colecionador em troca de fortuna e segredos. [112] Ao se infiltrar no castelo do Coletor, eles foram capturados. [116]Os Guardiões da Galáxia conseguiram se libertar quando Gamora fez um acordo ameaçador com o Colecionador para enganar o Grande Mestre, como parte de sua jornada para possuir a Joia da Alma.</p>
<p class="text">Enquanto os Guardiões marchavam de volta para o Grande Mestre, os Raptors atacaram Milano, uma oportunidade que seu líder Talonar aproveitou para recuperar as Nega-Bands que pertenciam ao herói Kree Mar-Vell . Rocket conseguiu manter uma das bandas, mas foi envenenado durante a luta por ela. [118] Quill trocou a banda por um antídoto e conseguiu banir Talonar para uma parte remota da galáxia. [119]Finalmente conhecendo o Grande Mestre, os Guardiões da Galáxia se viram envolvidos na guerra fraternal entre os dois Anciões do Universo, que inesperadamente terminou com uma trégua. O Grande Mestre e o Colecionador determinaram que os eventos por trás das Joias do Infinito desaparecidas e dos Anciões do Universo desaparecidos não eram uma coincidência e poderiam ajudá-los a descobrir maquinações secretas. [120] Como parte de suas investigações sobre o paradeiro das Joias do Infinito, os Guardiões visitaram a Terra. Milano foi infiltrado pelo herói que mudou de tamanho, o Homem-Formiga , que pediu para se juntar aos Guardiões como uma forma de abandonar a Terra após ser chantageado pelo Império Hidra caído .</p>
<p class="text">Os Guardiões foram alistados no corrompido Tropa Nova pelo Comandante Adsit , pois os Raptors representavam um inimigo comum. Transferidos para a Rocha , os Guardiões da Galáxia se juntaram à Tropa Nova e procuraram por infiltrados dentro dela. Além disso, foi revelado que Thanos havia escapado da custódia do Corpo. No Rock, Quill descobriu que seu amigo Nova, que aparentemente pereceu no Cancerverse, estava vivo. Eles se encontraram e procuraram por espiões desonestos em um posto de resistência liderado por Nova Eve Bakian no planeta Xitaung , onde a Pedra do Poder foi encontrada. Gamora e o Homem-Formiga descobriram que Ultron havia infectado incontáveis ​​almas com o Vírus Ultron.na galáxia, transformando-os em escravos ciborgues, e conseguiu resgatar alguns refúgios. [122] Ao mesmo tempo, Drax descobriu que os Novas ordenados pela Fraternidade dos Raptores haviam negociado a liberdade de Thanos para prejudicar a reputação da Tropa Nova. Isso levou o Nova Corps a começar a se livrar parcialmente de seus inimigos internos.</p>
<p class="text">Rocket finalmente argumentou que os Novas exemplares deveriam ser tratados como traidores, enquanto os desonestos deveriam compor sua força de ataque contra os Raptors. Enquanto isso, o exército arbóreo do Jardineiro ataca Luganenhum, levando Cosmo a convocar os Guardiões da Galáxia. Conforme os Guardiões eliminavam os soldados, Groot ganhava poder e crescia. Os Guardiões da Galáxia foram para Telferina para lutar contra o Jardineiro, quando Drax deixou o grupo e foi solicitado por Quill para guardar o forte de Bakian e a Joia do Poder. Subjugado por Thanos, o Chitauri tinha uma facção dissidente liderada pelo Warbringer para adquirir a Joia do Poder e libertar seu povo do Titã Louco. Drax protegeu a Pedra e os Novas de Talonar e do Warbringer. Em Telferina, os Guardiões libertaram o Jardineiro, restaurando Groot com todo o seu poder e faculdades. Em Xitaung, os Guardiões se juntaram a Drax . Ação. De volta a Luganenhum, Quill recebeu a Joia da Realidade do Grande Mestre e do Colecionador. Ele foi interrompido por versões de Phyla-Vell e Moondragon de uma Terra alternativa mais heróica que reivindicou a Pedra para si, pois ela veio de seu universo.</p>
<img class="img" src="img/guardioes5.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">Expondo as ações assassinas dos olimpianos sedentos de sangue , Nova interrompeu as férias dos Guardiões da Galáxia em Halfworld para buscar sua ajuda. Embora Gamora, Drax e Groot tenham se recusado por preocupação com a segurança da equipe, Quill, Rocket e os alternativos Phyla-Vell e Moondragon ajudaram Nova de bom grado pelas costas. Junto com o excêntrico Marvel Boy , a equipe improvisada embarcou em uma missão para destruir o Novo Olimpo . No processo de conclusão da operação, os Guardiões libertaram o prisioneiro olímpico Hércules. Enquanto isso, Quill teve que detonar manualmente uma bomba de buraco negro para completar a missão. Ao enviar os olímpicos para fora da realidade ao sequestrar o rotor dimensional do Novo Olimpo, Quill foi dado como morto.</p>
<p class="text">Os Guardiões da Galáxia foram devastados pela morte de Quill, fazendo com que a equipe se dividisse, com Gamora, Groot, Drax e o Moondragon original formando seus próprios Guardiões da Galáxia mercenários . As duas equipes rapidamente se encontraram em lados opostos de uma missão envolvendo a operação de mineração de recursos que ameaça o planeta do empresário inescrupuloso e inimigo de Rocket, Castor Gnawbarque , com a equipe de Gamora sendo contratada por ele e acompanhada pelo herói novato Prince of Power e o Halfworlder Blackjack O'Hare para derrubar seus antigos aliados. O confronto terminou em uma trégua durante a qual os dois Moondragons se fundiram em um único ser e Gnawbarque foi morto.</p>
<p class="text">Com a paisagem galáctica sofrendo diversas mudanças, os Guardiões da Galáxia se envolveram em sua política enquanto Marvel Boy e Nova participavam de reuniões para o Conselho Galáctico. Durante uma conferência diplomática, o Imperador Stote do Zn'rx e um agente da Aliança Kree/Skrull foram assassinados, com Marvel Boy sendo acusado do assassinato. Rocket liderou uma investigação ao lado dos Guardiões e descobriu que o Profiteer estava por trás das ações para desestabilizar a Galáxia iniciando um Snarkwar e lucrando com a venda de armas.</p>
<p class="text">A crise foi interrompida pela notícia de Knull devastando o universo com seus simbiontes. Os Guardiões da Galáxia defenderam Spartax da fúria, onde se reuniram com Quill, o lendário Senhor das Estrelas vivo. Ele viveu, sem envelhecer, no mundo de outra dimensão de Morinus por mais de cem anos e dominou sua vontade até que os olimpianos das trevas o encontraram e o levaram a retornar à sua realidade nativa para atraí-los para longe de seu novo lar. Os Guardiões se uniram para manter sua posição em Daedalus 5 para se opor aos deuses vingativos. Após a vitória da equipe, o Conselho Galáctico decidiu sancionar os Guardiões da Galáxia reformados como protetores do cosmos liderados por Nova à luz da crescente incerteza da paisagem galáctica, fornecendo-lhes um quartel-general na estação espacial Proscênio .</p>
<p class="text">Sua operação se expandiu como nunca antes e eles deram as boas-vindas a novos agentes em suas fileiras, como Kl'rt, o Super Skrull e os Quasars , Wendell Vaughn e sua parceira que compartilhava a existência com ele, Avril Kincaid . De acordo com o pedido da Aliança Kree/Skrull, os Guardiões responderam aos Progenitores atacando as ruínas de Hala e um grupo de cultistas de fogo heréticos Skrull no misteriosamente novo "Rimworld". Ao lado do Imperador Hulkling e sua consorte Wiccan , os Guardiões afastaram os Progenitores, mas foram surpreendidos pelo Doutor Destino. Ao lutar contra Doom, que havia transferido sua mente para Hulkling, os Guardiões conseguiram prendê-lo dentro do corpo de Rocket usando a telepatia de Moondragon. Enquanto isso, os outros Guardiões no "Rimworld" perceberam que os cultistas do fogo se basearam em Ego, o Planeta Vivo . A crise emergente levou os Guardiões da Galáxia a receber o Doutor Destino em suas fileiras para combater a ameaça. Logo, os Guardiões conheceram a natureza da ameaça que se seguiu, pois Ego estava possuído pelo senhor Faltine Dormammu , o terrível senhor da Dimensão das Trevas .</p>
<p class="text">Com a ajuda da Aliança Kree/Skrull , do Império Intergaláctico de Wakanda e da SWORD , os Guardiões afastaram a onda escura e interminável de Mindless Ones de Dormammu em suas tentativas de conquistar cinco planetas diferentes para usá-los como pontos de um pentagrama do tamanho de uma galáxia. para invocar toda a Dimensão das Trevas. Dormammu foi finalmente derrotado depois que uma parte dos Guardiões ajudou o Doutor Destino a realizar um ritual para sugar os poderes do demônio para si mesmo, dando ao resto dos Guardiões a oportunidade de usar o Retaliator Mark II para disparar uma bala gigante de Mysterium , um metal anti-mágico, infundido na Força Novae os poderes solares do Senhor das Estrelas. O ataque matou Ego e baniu Dormammu para a Dimensão das Trevas. O Doutor Destino partiu sem que os Guardiões soubessem que ele havia planejado a invasão aniquiladora de Dormammu para ter acesso a seus poderes. Após a guerra, os Guardiões da Galáxia finalmente tiveram a chance de aproveitar as férias juntos.</p>
<img class="img" src="img/guardioes6.jpg" rcset style="width: 1305px; height: 400px;">
<h1 class="titulo">Quem São os Guardiões da Galáxia</h1>
<div class="blocos">
    <div class="conteudo1">
        <div class="card">   
            <div class="guardioes">
                <img class="img1" src="img/starlord.jpg" rcset style="width: 300px; height: 300px;">
                <h1 class="vc1">Star Lord</h1>
                <h1 class="oi1">O líder</h1>
                <p class="text1"> O semi Deus filho do planeta Ego, foi abdusido quando criança após a morte de sua mãe a pedido do seu pai , assim ele foi criado pelos saqueadores se tornando o maior ladrão da galáxia , atualmente ele se juntou aos guardiões e lídera o grupo como o senhor das galáxias, atualmente ele se encontra apaixonada pela Gamora.</p>
            </div>
        </div>
        <div class="card">
            <div class="guardioes">
                <img class="img1" src="img/gamora.jpg" rcset style="width: 300px; height: 300px;">
                <h1 class="vc2">Gamora</h1>
                <h1 class="oi2">A Assassina</h1>
                <p class="text1">Quando criança o Titã louco Thanos matou 50% de toda a população de seu planeta, após esse episódio ele fez questão de a adotar como filha e a criar a ensinando a dominar a arte da chacina dominando mundos e exterminando populações, atualmente ela se tornou membro dos guardiões e se vingou de seu pai Thanos por tudo que ele a fez passar.  </p>
            </div>
        </div>
        <div class="card">
            <div class="guardioes">
                <img class="img1" src="img/rocket.jpg" rcset style="width: 300px; height: 300px;">
                <h1 class="vc4">Rocket Racoon</h1>
                <h1 class="oi4">O Mais Inteligente</h1>
                <p class="text1">Quando filhote foi capturado no planeta terra para ser levado ao laboratório do grande vilão da Galáxia o Alto Evolucionário o qual atraves de seus experimnetos modificou Rocket um guaxinin comum em um ser racional , que fala e tem sua inteligência elevada a grandes gênios do universo, atualmente ele é um dos principais dos Guardiões. </p>
            </div>  
        </div>  
        <div class="card">
            <div class="guardioes">        
                <img class="img1" src="img/groot.jpg" rcset style="width: 300px; height: 300px;">
                <h1 class="vc5">Groot</h1>
                <h1 class="oi5">O Imortal</h1>
                <p class="text1">  Groot era o último integrante dos Colossos Florais e foi aprisionado pelos Kree no planeta Hala. Foi nesse aprisionamento onde ele começou sua amizade com Rocket Racoon e a partir daí é designado para uma equipe de operações secretas liderada pelo Senhor das Estrelas, sim “Os Guardiões da Galáxia”. Groot é o imortal do grupo.</p>
            </div>
        </div>
    </div>
    <br>
    <div class="conteudo2">
        <div class="card">   
            <div class="guardioes">
                <img class="img1" src="img/drax.jpg" rcset style="width: 300px; height: 300px;">
                <h1 class="vc3">Drax</h1>
                <h1 class="oi3">O Destruidor</h1>
                <p class="text1">Drax era um ser feliz até o aparecimento do Thanos em seu mundo exterminando metade do seu povo entre eles estavam sua filha e mulher, após esse episódio Drax destina a sua vida a se vingar do Thanos, atualmente ele é membro dos Guardioẽs e destina sua vida salvando a Gálaxia com sua equipe sendo o mais forte dentre eles.</p>
            </div>
        </div>
        <div class="card">
            <div class="guardioes">
                <img class="img1" src="img/mantis.jpg" rcset style="width: 300px; height: 300px;">
                <h1 class="vc6">Mantis</h1>
                <h1 class="oi6">A Telepáta</h1>
                <p class="text1">Mantis pode sentir e manipular as emoções dos outros. Ela consegue estimular a preguiça, podendo fazer alguém dormir, ou estimular a raiva e etc. Mantis com a sua empatia pode se comunicar com plantas. Mantis é irmã do Senhor das Estrelas e também faz parte dos Guardioẽs sendo se tornando uma das mais queridas do grupo</p>
            </div>
        </div>
        <div class="card">
            <div class="guardioes">
                <img class="img1" src="img/nebulosa.jpg" rcset style="width: 300px; height: 300px;">
                <h1 class="vc7">Nebulosa</h1>
                <h1 class="oi7">A Meia Máquina</h1>
                <p class="text1">Nebulosa também conhecida como Nebula,é uma ciborgue Luphomoide. Criada como filha de Thanos, a personagem começa a jornada como uma antagonista, guiada pela vingança e pela inveja, principalmente contra Gamora. Atualmente ela e sua irmã Gamora se entenderam e lutam juntas para salvar a galáxia junto dos Guardioẽs</p>
            </div>
        </div>
        <div class="card">
            <div class="guardioes">        
                <img class="img1" src="img/adam.jpg" rcset style="width: 300px; height: 300px;">
                <h1 class="vc9">Adam Warlock</h1>
                <h1 class="oi9">O Super Poderoso</h1>
                <p class="text1">É um humano sintético criado pelo Enclave e possui vários poderes. Absorção de energia, super-força, super-velocidade entre outras habilidades.No grande esquema das coisas, Adam Warlock é simplesmente mais poderoso do que Thanos. Isso também, muito provavelmente, se aplica ao MCU, mesmo se Thanos não estivesse morrido.</p>
            </div>
        </div> 
    </div>
</div>
<br>
<a href="?page=marvels.php">Acessar a Comunidade Nerd</a>