<img class="img" src="img/sexteto.jpg" rcset style="width: 1305px; height: 400px;">
<h1 class="titulo"> O Sexteto Sinistro</h1>
<p class="text">Depois de sofrer três derrotas consecutivas do escalar de paredes, o super-herói de lançador de teia Homem-Aranha, Doutor Octopus percebeu que precisava de assistência de outros para derrotar o Homem-Aranha. Ele entrou em contato com todos os super-vilões conhecidos do Homem-Aranha e apenas cinco responderam: o assassino no ar Abutre, o eletrizante Electro, o selvagem Kraven, o Caçador, o misterioso mestre das ilusões Mystério, e o metamorfo Homem-Areia. Sabendo que ele nunca seria capaz de manter a equipe unida por muito tempo, o Doutor Octopus rapidamente formulou um plano de batalha que daria a cada um dos vilões a glória pessoal e o Homem-Aranha uma morte prematura. Cada membro individual do Sexteto Sinistro lutaria contra o Homem-Aranha em um local cuidadosamente escolhido, até o ponto em que o rastreador de paredes não existisse mais.</p>
<p class="text">O próprio Homem-Aranha tinha seus próprios problemas, pois de alguma forma ele perdera seus poderes e se preparava para voltar à vida normal na adolescência. Enquanto se culpava pela morte de seu tio Ben Parker, o Aranha perdeu o equilíbrio e caiu do lado de um prédio, aterrissando e agarrando-se a um mastro de bandeira. Como Peter retornou à sua vida normal como estudante e fotógrafo freelancer, ele não sabia do fato de que o Sinister Six percebeu que a secretária do Clarim Diário Betty Brant desempenhou um grande papel na vida do Homem-Aranha e capturam-a, juntamente com uma inocente espectadora - a tia de Peter May Parker.</p>
<p class="text">Foi então deixado para o Abutre derramar o feijão para J. Jonah Jameson, avisando-o para informar ao Homem-Aranha que Betty estava sendo refém junto com a tia May e se ele queria vê-los vivos, ele teria que lutar contra o Sexteto Sinistro.</p>
<p class="text">Apesar de não ter seus poderes, Peter vestiu sua fantasia de Homem-Aranha e foi lutar com Electro em uma usina elétrica. Durante a batalha, Peter de alguma forma recuperou seus superpoderes (especula-se que seja um bloqueio psicológico, causado por sua auto-aversão pela perda de seu tio, que ele superou quando enfrentou uma situação de vida ou morte) e facilmente derrotou o Electro. O Aranha, em seguida, lutou contra Kraven o Caçador, que o confrontou com alguns gatos selvagens e derrotou este inimigo também. Depois de derrotar o Mystério (que utilizou duplicações robóticas dos X-Men originais), o Homem-Areia que encurralou o rastejador de paredes e ele mesmo em uma câmara indestrutível e sem ar e o Abutre, Aranha enfrentou o Dr. Ock, que o atraiu para um enorme aquário. Os dois inimigos lutaram e o Homem-Aranha foi vitorioso. Todos os seis super-vilões foram posteriormente enviados para a prisão.</p>
<img class="img" src="img/sexteto1.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">O Sexteto Sinistro apareceu pela primeira vez em Amazing Spider-Man Annual #1, de 1964. Isso aconteceu depois que o Doutor Octopus sofreu derrotas consecutivas após lutar contra o cabeça-de-teia, e decidiu convidar vários inimigos jurados do Homem-Aranha a unir forças para derrotá-lo.</p>
<p class="text">Vários vilões vieram e compraram a ideia do Doutor Octopus. Essa primeira formação do Sexteto Sinistro contava com Electro, Mysterio, Homem-Areia, Abutre e Kraven, o Caçador. Surpreendentemente, embora o grupo tenha se juntado porque sozinhos não conseguiam derrotar o Aranha, o seu plano de ataque como equipe foi… atacar o herói separadamente, um de cada vez, em diferentes ocasiões. Sim, o Doutor Octopus é considerado um dos maiores gênios do Universo Marvel – não sei o que rolou com ele aqui.</p>
<p class="text">Os quadrinhos da Marvel tiveram vários crossovers épicos, e isso na verdade se tornou uma marca registrada da editora entre os leitores nos anos 60, já que na DC era muito mais difícil os heróis se encontrarem. E foi justamente na edição da primeira aparição do Sexteto Sinistro que os leitores viram pela primeira vez o Homem-Aranha dando de cara com vários outros super-heróis publicados na época, como Doutor Estranho, X-Men, Homem de Ferro, Thor e Capitão América.</p>
<p class="text">Embora eles tenham funcionado mais como participações especiais do que como parte da história, isso não tinha acontecido antes e se tornou algo recorrente nos quadrinhos da Marvel dali para frente. Embora o Homem-Aranha já tivesse encontrado o Quarteto Fantástico, por exemplo, essa foi a primeira vez que os leitores realmente se sentiram dentro de um universo coeso onde os heróis poderiam se esbarrar a qualquer momento em Nova York.</p>
<img class="img" src="img/sexteto2.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">Depois que o Sexteto Sinistro original se desfez no final de Amazing Spider-Man Annual #1, levou mais 25 anos até que a equipe retornasse, algo que aconteceu em Amazing Spider-Man #334. Ao contrário da primeira vez, eles agora decidem atacar o Homem-Aranha juntos – o que faz muito mais sentido, convenhamos.</p>
<p class="text">Essa segunda versão da equipe conta basicamente com os mesmos membros, com exceção do Duende Macabro, que entrou no lugar de Kraven. O Caçador havia morrido recentemente nas páginas de A Última Caçada de Kraven, uma das histórias mais icônicas do Homem-Aranha.</p>
<p class="text">Embora o Sexteto Sinistro tenha aparecido em Homem-Aranha: A Série Animada, de 1994, o grupo era um pouco diferente de como apresentado nos quadrinhos. Rhino, Escorpião, Camaleão e Shocker faziam parte da equipe, por exemplo.Mas a maior diferença em relação aos quadrinhos é que eles não eram chamados de Sexteto Sinistro, mas sim de Os Seis Traiçoeiros. A mudança ficou por conta dos censores da Fox Kids, que achavam que a palavra “Sinistro” seria muito assustadora para as crianças. Curiosamente, X-Men: A Série Animada contava com a presença do vilão Senhor Sinistro. Enfim, a hipocrisia.</p>
<p class="text">Apesar do nome, o Sexteto Sinistro em várias ocasiões contou com mais de seis membros na equipe. Mas foi no arco “Caído Entre os Mortos”, de Mark Millar, que fomos apresentados à formação com mais membros da equipe: nada mais nada menos que 12 supervilões!,Esse grupo foi fundado pelo Duende Verde e consistia em Escorpião, Abutre, Homem-Areia, Electro, Camaleão, Lagarto, Homem-Hídrico, Shocker, Cabeça-de-Martelo, Boomerang e também Tombstone.</p>
<img class="img" src="img/sexteto3.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">A Terra Selvagem é conhecida por ser o lar de Ka-Zar, mas é também onde fomos apresentados ao alienígena Gog. Em Amazing Spider-Man #103, J. Jonah Jameson, Peter Parker e Gwen Stacey vão para a Terra Selvagem. Não demora muito para Gog aparecer e sequestrar Gwen, levando-a para Kraven, que planeja torná-la a rainha de seu novo mundo.</p>
<p class="text">Ele foi enviado mais tarde para outra dimensão, mas o Doutor Octopus o resgatou, finalmente recrutando o guerreiro alienígena para se juntar ao Sexteto Sinistro. Gog acaba sendo enviado de volta para a dimensão de onde veio pelo Senhor Fantástico e, infelizmente, nunca realmente causou o impacto que Octopus esperava como o membro final do Sexteto Sinistro em sua terceira iteração.</p>
<p class="text">Embora o grupo tenha sido formado porque seus membros odiavam o Homem-Aranha, o inimigo do Sexteto Sinistro nem sempre é Peter Parker. Obviamente, eles enfrentaram outras versões do Homem-Aranha, como Miles Morales e Ben Reilly, o Aranha Escarlate. Na verdade, o Sexteto Sinistro enfrentou até mesmo o Doutor Octopus, quando ele estava no corpo de Peter Parker agindo como Homem-Aranha Superior.</p>
<p class="text">Além de personagens relacionados ao Homem-Aranha, como Kaine, o Sexteto Sinistro também pode ser considerado inimigo de vários outros personagens da Marvel. Até mesmo o Homem de Ferro já os enfrentou.</p>
<img class="img" src="img/sexteto4.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">O principal objetivo da formação do Sexteto Sinistro era derrotar o Homem-Aranha, que se tornou o inimigo mortal dos supervilões do grupo. No entanto, no arco “Nos Confins da Terra”, de Dan Slott, o grupo novamente liderado pelo Doutor Octopus tem um plano novo e mais sinistro: destruir o mundo.</p>
<p class="text">Isso aconteceu quando o Doutor Octopus descobriu uma nova tecnologia que poderia acelerar o aquecimento global. Dessa vez, como o caso era bem mais grave, o Homem-Aranha contou com a ajuda dos Vingadores, da S.H.I.E.L.D. e de vários outros super-heróis para derrotar o Sexteto Sinistro.</p>
<p class="text">No arco do Homem-Aranha Superior, o Doutor Octopus transferiu sua consciência para o corpo de Peter Parker. Nessa época, enquanto agia no lugar do herói, ele acabou enfrentando o Sexteto Sinistro, que agora era liderado pelo Bumerangue.</p>
<p class="text">Curiosamente, o Doutor Octopus teve a ideia de liderar o grupo novamente. No entanto, isso não foi feito para cometer uma série de atos criminosos como sempre, afinal agora ele era o Homem-Aranha. Assim surgia o Sexteto Superior, trabalhando do lado correto da lei e até mesmo capturando alguns outros vilões.</p>
<img class="img" src="img/sexteto5.jpg" rcset style="width: 1305px; height: 400px;">
<p class="text">Durante anos, a Sony esteve completamente obcecada em fazer um filme do Sexteto Sinistro. O diretor seria Drew Goddard, que queria fazer um filme que remetesse a longas como Os Doze Condenados e Meu Ódio Será Sua Herança, onde, embora os personagens sejam vilões, os espectadores ainda podem torcer por eles.</p>
<p class="text">Várias trocas de e-mail que a Sony teve com Goddard revelaram grandes detalhes sobre seus planos para o filme e aparentemente seria bem louco. Uma grande parte da história teria acontecido na Terra Selvagem, uma região tropical escondida criada por alienígenas na Antártica.</p>
<p class="text">A equipe de vilões estaria lutando contra dinossauros, e o vilão principal provavelmente seria Gog, o alienígena que vive por lá. Ah, e apesar de ser um filme com seis grandes inimigos do Homem-Aranha, o próprio herói aracnídeo não iria aparecer. Alguém acha que isso daria certo?</p>
<img class="img" src="img/sexteto6.jpg" rcset style="width: 1305px; height: 400px;">
<a href="?page=marvels.php">Acessar a Comunidade Nerd</a>