<img class="img" src="img/x.jpg" rcset style="width: 1310px; height: 400px;">
<h1 class="titulo">OS X-MENS</h1>
<a class="text">Os X-Men surgiram originalmente em 1963, fazendo parte de uma série de novas idéias e títulos propostos pelo editor Stan Lee, da editora Marvel Comics.</a>
<a class="text">Lee, no caso, tal como já havia feito com outras de suas criações, dava continuidade à exploração de um novo modelo de personagens de quadrinhos do gênero super-heróis. Essa então recente proposição super-heroística mesclava ironia e características anti-heróicas, à época pouco comuns aos personagens das revistas de histórias em quadrinhos, trazendo heróis que conviviam com problemas ou dificuldades que também poderiam afetar o leitor comum, como a incompreensão dos semelhantes, dificuldades econômicas, conflitos com autoridades policiais e crises de consciência. A fórmula já havia apresentado ótimos resultados com o monstro verde Hulk (1962) e com o desajustado adolescente Peter Parker, o Homem-Aranha (que também havia começado ficcionalmente a grudar suas teias nos prédios da cidade de Nova York em 1962), entre outros.
</a>
<a class="text">Infelizmente, o grupo de adolescentes com poderes mutantes devido à exposição da geração anterior à energia atômica – originalmente composto por Cíclope, Garota Marvel, Anjo, Fera e Homem de Gelo e orientado por um tutor paternal e compreensivo, o Professor Charles Xavier, também ele um mutante -, não conseguiu nem de longe se aproximar do sucesso dos personagens anteriores. Apesar do trabalho artístico sempre admirável do mestre Jack Kirby e da proposta temática interessante, eles não conseguiram passar, em seus primeiros anos de participação na falange Marvel, de heróis de terceira ou, no máximo, segunda categoria. Colocação injusta, sim.</a>
<a class="text">Mas, à época, real e provavelmente justificada. Afinal, tratava-se apenas de mais um grupo de heróis surgidos na esteira da ameaça nuclear, que combatiam malfeitores de mesma origem (a chamada Irmandade de Mutantes, chefiada pelo vilão Magneto). Nas primeiras aventuras da equipe, nem sequer se cogitava a respeito da dicotomia Martin Luther King e Malcolm X, que posteriormente veio a centralizar, respectivamente, as análises das figuras dos líderes dos X-Men e da Irmandade.</a><br><br>
<img class="img" src="img/x1.jpg" rcset style="width: 1310px; height: 400px;"><br><br>
<a class="text">Pouca influência tiveram nesse panorama desfavorável as primeiras mudanças de equipe de produção que ocorreram no título dos heróis mutantes, ainda que dela fizessem parte um bom roteirista (Roy Thomas) e um ótimo desenhista (Neal Adams).</a>
<a class="text">A partir do número 67, as histórias inéditas deixaram de ser produzidas, e reprises começaram a preencher as páginas da revista, uma situação que durou até o número 93. A partir do número 94 um novo roteirista, Chris Claremont, assumiu as histórias dos Filhos do Átomo.</a>
<a class="text">A chegada de Claremont foi antecedida por uma edição especial com os jovens heróis, Giant Size X-Men 1, com capa datada de maio de 1975. Na edição, após a equipe original desaparecer em uma ilha do Pacífico, seu mentor toma a decisão de convocar uma equipe de resgate, denominada de Novos X-Men, para procurá-los.</a>
<a class="text">Essa equipe era bem mais variada e multi (ou pluri) nacional do que a anterior. Dela faziam parte um teleportador alemão de cor azul (Noturno), uma africana com domínio do clima (Tempestade), um camponês russo que transformava seu corpo em aço (Colossus), um nativo norte-americano com força e resistência extraordinárias (Pássaro Trovejante), um canadense que fazia lâminas de aço brotar das juntas de sua mão (Wolverine), um irlandês com capacidade de dar gritos supersônicos (Banshee) e um japonês que disparava labaredas e produzia calor (Solaris). Os responsáveis por essa história emblemática, verdadeiro marco da saga dos hoje quase cinquentões X-Men foram o roteirista Len Wein e o desenhista Dave Cockrum.</a><br><br>
<img class="img" src="img/x2.jpg" rcset style="width: 1310px; height: 400px;"><br><br>
<a class="text">Com o número especial, montou-se o palco no qual, nos anos seguintes, brilharia a estrela de Chris Claremont, que se tornou o escritor oficial da série a partir de então e pode ser diretamente responsabilizado por seu sucesso posterior. A revista dos novos X-Men rapidamente se tornou a campeã de vendas e de aclamação da crítica da Casa das Ideias. E essa popularidade apenas aumentou quando outra figura emblemática da indústria de revistas em quadrinhos, o britânico John Byrne, assumiu a parte gráfica das histórias. Escritor e desenhista se completaram de uma forma verdadeiramente harmoniosa.</a>
<a class="text">Os dois artistas iriam revigorar o título e levá-lo a alturas que poucos haviam atingido, permanecendo à frente dele – juntamente com o arte-finalista Terry Austin – até finais dos anos 1980. Ampliaram-se os conflitos entre os diversos personagens, que passaram a ter grande papel nos enredos e aventuras, como o que envolveu o líder da equipe Cíclope e o sempre insatisfeito Wolverine. O estilo de liderança do primeiro colide diretamente com o espírito de discordância do segundo. Aos poucos, os artistas introduzem nas histórias a noção de que o grupo é mais do que a soma de suas partes. </a>
<a class="text">Segundo Richard Reynolds em seu livro Super Heroes: a modern mythology (London: Batsford, c1992), “Byrne e Claremont também introduziram noções Cabalísticas sobre a mística Árvore da Vida no roteiro, para reavivar o tema Gestalt do grupo mutante – que pode em si mesmo ser ligado ao romance de Theodore Sturgeon, More than Human”. Esse livro, originalmente publicado em 1953, trata de um grupo de seis pessoas com poderes extraordinários que é capaz de mesclar suas habilidades, conseguindo agir como um único organismo.</a>
<a class="text">Da colaboração dos dois autores surgiram durante os anos 1970 e 1980, algumas das sagas mais aclamadas vividas pelo grupo de heróis. Na de Proteus, enfrentam um mutante assassino. Na da Fênix Negra, assistem à Jean Grey, a Garota Marvel, transformar-se em uma poderosa entidade depois se sacrificar para salvar o mundo. Em "Dias de um futuro Esquecido" defrontam-se pela primeira vez com o conceito de realidades alternativas. E na história "Deus Ama, o Homem Mata", enfrentam pela primeira vez a realidade do preconceito dos humanos em relação aos mutantes.</a><br><br>
<img class="img" src="img/x3.jpg" rcset style="width: 1310px; height: 400px;"><br><br>
<a class="text">A dupla Claremont/Byrne eventualmente se desfez e cada um seguindo o seu caminho. O término da parceria, no entanto, felizmente não conseguiu ter reflexo muito negativo nas histórias dos X-Men, que permaneceram ainda sob a batuta de Claremont durante algum tempo, enquanto Byrne se transferia para outro título.</a>
<a class="text">Ambos haviam plantado em solo fértil as sementes da popularidade do grupo de mutantes, que permaneceram inalteradas nas décadas seguintes, passando a fazer parte de suas características distintivas. Inclusive, várias das premissas que eles desenvolveram em suas narrativas foram incorporadas à própria mitologia dos heróis e posteriormente aproveitadas nas diversas produções cinematográficas sobre eles.</a>
<a class="text">De fato, o primeiro filme dos X-Men trouxe novo vigor às películas centrados nos super-heróis, demonstrando cabalmente que era possível reproduzir nas grandes telas, graças ao avanço tecnológico, as características desses personagens, sem necessariamente levá-los ao ridículo. </a>
<a class="text"> Nesse sentido, foram um marco tanto para o cinema como para o gênero de quadrinhos ao qual esses personagens pertencem. Em produções bem elaboradas, sob direções seguras, todas as realizações centradas nos Filhos do Átomo possibilitaram a ampliação de sua popularidade, a ampliação de seu público leitor e a manutenção de seu título nas bancas, num círculo virtuoso que, felizmente, ainda não parece próximo de seu encerramento. Tudo indica, inclusive, que a próxima produção desses personagens a atingir as grandes telas continuará nessa mesma linha.
</a><br><br>
<img class="img" src="img/x4.jpg" rcset style="width: 1310px; height: 400px;"><br><br>
<h1 class="titulo">Em resumo os Ex-mens são:</h1>
<a class="text">X-Men é uma equipe de super-heróis de histórias em quadrinhos épicas publicadas nos Estados Unidos pela Marvel Comics. Criados por Stan Lee e Jack Kirby, estrearam em The X-Men #1, publicada em setembro de 1963, e era formado inicialmente pelo Professor X, fundador da equipe, Ciclope, Fera, Homem de Gelo, Anjo e Garota Marvel (Jean Grey).</a>
<a class="text">Os X-Men são mutantes: humanos que, como resultado de um súbito salto evolucionário, nasceram com habilidades super-humanas latentes, que geralmente se manifestam na puberdade. Consequentemente no espaço, em suas histórias, vários homens comuns têm um intenso medo e/ou desconfiança dos mutantes (cientificamente chamados de Homo superior), que são vistos pelos cientistas em geral como o novo degrau da evolução humana. Logo, muitos os consideram uma ameaça à própria sociedade humana, fato intensificado por mutantes que usam seus poderes para fins criminosos.</a>
<a class="text">Para combater estes "mutantes malignos" (tais como Magneto e sua Irmandade de Mutantes) e promover a coexistência pacífica entre as duas raças, o benevolente Professor Charles Xavier (ou Professor X, o milionário que é, secretamente, um dos maiores telepatas da Terra), fundou uma academia para treinar jovens mutantes e doutriná-los em seu sonho de "harmonia inter-racial". Ocultando sua real intenção do restante do mundo sob a fachada do Instituto Xavier Para Jovens Super-Dotados, Charles deu, assim, início ao seu sonho.</a>
<a class="text">As histórias dos X-Men contam com personagens de diversas etnias sendo, talvez, a revista em quadrinhos mais multicultural já publicada pela Marvel. Este aspecto foi introduzido quando o título, que havia sido cancelado, pois a revista Abril Jovem não gostou da ideia dos X-Men, então seu verdadeiro criador fez uma viagem aos Estados Unidos com sua ideia dos X-Men para a Marvel tornando-se um sucesso da época e foi retomado nos anos 1970. Nesta década, o elenco (que contava apenas com mutantes americanos) foi diversificado, adicionando-se personagens da Alemanha (Noturno), Irlanda (Banshee), Canadá (Wolverine), União Soviética (Colossus), Quênia (Tempestade) e Japão (Solaris). Personagens representando várias outras etnias e cenários culturais foram subsequentemente adicionados. As histórias também retratavam temas relacionados ao status das minorias, incluindo assimilação, tolerância e crenças na existência de uma "raça superior".</a>
<a class="text">Os X-Men se expandiram para o cinema e televisão, incluindo alguns dos mais bem-sucedidos desenhos animados exibidos no Brasil nas manhãs de sábado: X-Men: Animated Series, X-Men Evolution e também Wolverine and the X-Men. O ano 2000 viu a estreia bem-sucedida de X-Men, filme dirigido por Bryan Singer. Sua sequência X2: X-Men United foi lançada em 2003, novamente sob direção de Singer, e um terceiro filme, X-Men: The Last Stand, desta vez dirigido por Brett Ratner, foi lançado em 26 de maio de 2006. Em 3 de Junho de 2011, a 20th Century Fox lançou X-Men: First Class (X-Men: Primeira Classe) onde conta como Charles Xavier (Professor X) e Erik Lehnsherr (Magneto) se conheceram e como se tornaram inimigos. Em 23 de maio de 2014, foi lançado X-Men: Dias de um Futuro Esquecido, filme baseado no arco de mesmo nome. Em 19 de maio de 2016, foi a estreia de X-Men: Apocalipse.</a><br><br>
<img class="img" src="img/x5.jpg" rcset style="width: 1310px; height: 400px;"><br><br>
<h1 class="titulo">História</h1>
<a class="text">Os X-Men foram fundados pelo Charles Francis Xavier, o Professor Xavier, para defender seu sonho de "convivência pacífica entre humanos e mutantes", ao mesmo tempo em que, secretamente, defendiam a humanidade dos "mutantes do mal". Assim, desde sua fundação, os X-Men vivem em uma constante batalha, "defendendo um mundo que os teme e odeia".</a>
<a class="text">Os primeiros números da revista também introduziram os arqui-inimigos da equipe: Magneto (Erik Magnus Leinsher) e sua Irmandade de Mutantes, composta por Mercúrio (Pietro Maximoff), Feiticeira Escarlate (Wanda Maximoff) - ambos irmãos de sangue e filhos adotivos de Magneto -, Mestre Mental e Groxo. Nesta fase também surgiram inimigos que ainda viriam dar muito trabalho aos "filhos do átomo" (ou nem tanto), como Fanático, Blob e Vanisher.</a>
<a class="text">Em 1969, nos E.U.A., o escritor Roy Thomas e o desenhista Neal Adams rejuvenesceram a franquia e introduziram dois novos personagens, Destrutor (Alex Summers), irmão de Ciclope e Polaris (Lorna Dane). No entanto essas primeiras edições de X-Men não foram bem sucedidas em vendas e a Marvel parou de produzir novas histórias a partir do #66. Depois de um hiato, a série continuou com reimpressões do material antigo entre os #67 e 93.</a>
<h1 class="titulo">Racismo</h1>
<a class="text">Na fase do roteirista Chris Claremont, o Professor X já foi comparado ao líder pelos direitos civis dos afro-americanos Martin Luther King Jr, e Magneto ao militante mais agressivo Malcolm X.[4][5] Os X-Men se referem muitas vezes ao "sonho de Xavier", o que leva a crer em uma referência à famosa frase de Martin Luther King, "Eu tenho um sonho". As revistas X têm com frequência mostrado mutantes como vítimas de violência, evocando o linchamento de afro-americanos na época anterior ao movimento pelos direitos civis americano.</a>
<a class="text">Ainda que esta interpretação tenha se tornado lugar-comum, ela não é livre de críticas. Em 2002, o crítico de quadrinhos Julian Darius afirmou, no artigo "X-Men não é uma alegoria à tolerância racial", que um exame mais detalhado do começo dos X-Men nos quadrinhos revelará Magneto não como Malcolm X, mas como os revolucionários radicais Panteras Negras. Os Sentinelas teriam sido criados para representar forças opressivas, como a KKK, como forma de negar as emendas e os direitos civis dos mutantes. Nos primeiros quadrinhos, Xavier parecia não se importar com os direitos dos mutantes, mantendo o foco na repressão dos mutantes malignos. Ele era, segundo Darius, claramente um contrarrevolucionário. Somente com a evolução da série o Professor X passou a atuar como um "ativista mutante", criando inclusive a Resistência Mutante.</a>
<h1 class="titulo">Antissemitismo</h1>
<a class="text">Outra comparação mais explícita é com o antissemitismo. Magneto, um sobrevivente do Holocausto, vê a situação mutante muito parecida com a dos judeus na Alemanha nazista. Em um momento, durante um episódio da série de 1992, X-Men: Animated Series, ele chega a usar as palavras: "Nunca mais". Nos quadrinhos, Magneto tem rotineiramente buscado estabelecer uma nação mutante. O campo de concentração para trabalho forçado de mutantes na ilha de Genosha, nos quais números eram marcados nas cabeças dos mutantes, teve muito em comum com os campos de concentração nazistas, assim como os campos de concentração da clássica história Dias de um Futuro Esquecido.</a>
<h1 class="titulo">Medo Comunista</h1>
<a class="text">Ocasionalmente, alusões ao medo dos comunistas estão presentes. O senador Robert Kelly propôs um "Ato de Registro de Mutantes", similar aos esforços do Congresso americano para banir os comunistas dos Estados Unidos. No filme X-Men de 2000, o senador exclama: "Nós precisamos descobrir quem são esses mutantes, e o que eles podem fazer."</a>
<h1 class="titulo">Como Subcultura</h1>
<a class="text">Em alguns casos, particularmente nas histórias de Grant Morrison em Novos X-men e Peter Milligan em X-statix, no começo dos anos 2000, os mutantes são tratados como uma subcultura distinta, com "bandas mutantes", e um popular desenhista de moda mutante, que criou roupas especiais para a fisiologia mutante. Também a série Distrito X e X-Factor tem como ambientação uma área de Nova York chamada Cidade Mutante. Deste modo, os X-Men podem servir como alegoria para qualquer minoria da população que estabeleça uma subcultura específica.
</a>
<a class="text">O diretor Bryan Singer tem demonstrado isso com diferentes raças e orientações sexuais, e a franquia X-men tem servido como metáfora da aceitação de todas as pessoas por seus dons únicos e especiais. O poder mutante que deve ser escondido do mundo é uma analogia ao sentimento de diferença e medo, normalmente sentido por todos durante a adolescência. Parte da atração de X-men é oferecer um santuário para explorar e celebrar abertamente suas diferenças com uma subcultura única.
</a>
<h1 class="titulo">Locais Fictícios</h1>
<a class="text">Genosha, uma nação insular africana fictícia, localizada perto de Madagascar, que viveu durante longo tempo um regime de apartheid contra mutantes.</a>
<a class="text">Madripoor, uma ilha no Sudeste da Ásia, capital de um principado próxima de Singapura, tendo como "Senhora do Crime" a vilã Víbora (antiga Madame Hidra).</a>
<a class="text">Ilha Muir, uma ilha escocesa, geralmente lembrada como sendo o local onde ficava o laboratório da Dr. Moira McTaggert, a famosa geneticista humana, aliada de Charles Xavier.</a>
<a class="text">Terra Selvagem, um local pré-histórico escondido na Antártida, com dinossauros, alienígenas e outros seres estranhos.</a>
<a class="text">Krakoa, a "Ilha-Viva", responsável pelo surgimento da segunda geração de X-Men.</a>
<a class="text">Utopia, ilha na costa de São Francisco, que está servindo de refúgio para os mutantes restantes após os eventos da série Utopia.</a>
<a class="text">Sala de Perigo é um lugar de treinamento para os X-Men, criada pelo Professor Xavier para projetar cenários simulados. Os maiores vilões dos X-Men da Sala de Perigo são os Sentinelas, robôs gigantescos e com grande um poder. Houve muitos problemas com a Sala de Perigo, na manutenção e no próprio controle.</a><br><br>
<img class="img" src="img/x6.jpg" rcset style="width: 1310px; height: 400px;"><br><br>
<div  class="pagina">   
    <a href="?page=marvels.php">Acessar a Comunidade Nerd</a>
</div>